import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/componant/layout/header'
import Topbar from '@/componant/layout/topbar'
import Footer from '@/componant/layout/footer'
import ContactForm from '@/componant/elements/contactForm'
import TopCollege from '@/componant/elements/topCollege'
import WhyTheCareer from '@/componant/elements/whyTheCareer'
import AdvantagesOfStudying from '@/componant/elements/advantagesOfStudying'
import OurService from '@/componant/elements/ourService'
import EligibilityCriteria from '@/componant/elements/eligibilityCriteria'
import ReachUs from '@/componant/elements/reachUs'
import BannerSlider from '@/componant/elements/BannerSlider'
import AdmissionProcdure from '@/componant/elements/admissionProcdure'
import BannerForm from '@/componant/elements/BannerForm'
// import BannerSlider from '@/componant/elements/slider'
// import AdmissionProcdure from '@/componant/elements/AdmissionProcdure'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Web Page Task</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" ></link> */}
      </Head>
      <main >
        {/* <h1>Hello </h1> */}
        <Topbar />
        {/* <Header /> */}
        <BannerForm />
        {/* <BannerSlider />
       
        <ContactForm /> */}
        <TopCollege />
        <WhyTheCareer />
        <AdvantagesOfStudying />
        <OurService />
        <EligibilityCriteria />
        <AdmissionProcdure />
        <ReachUs />
       
        <Footer />


        {/* <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> */}
      </main>
    </>
  )
}
